/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContentViewerTemplate: typeof import('./src/components/ContentViewerTemplate.vue')['default']
    ResourceList: typeof import('./src/components/ResourceList.vue')['default']
    TagAdder: typeof import('./src/components/TagAdder.vue')['default']
  }
}
