/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContentEditorTemplate: typeof import('./src/components/ContentEditorTemplate.vue')['default']
    ContentViewerTemplate: typeof import('./src/components/ContentViewerTemplate.vue')['default']
    MainPage: typeof import('./src/components/MainPage.vue')['default']
    MainSearch: typeof import('./src/components/MainSearch.vue')['default']
    ResourceList: typeof import('./src/components/ResourceList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagAdder: typeof import('./src/components/TagAdder.vue')['default']
  }
}
